### ISSUE TITLE
Bottom sheet back navigation from scrim area

### ISSUE THREAD

**Issue by fraherm** [freeletics/mad#365]
The back navigation from a bottom sheet feature by clicking on the scrim area (greyed out area) prevents further navigation afterwards.
The simple sample can be used to demonstrate and debug the issue.

Issue:

* Open the bottom sheet by clicking on the "Bottom Sheet" text
* Dismiss the bottom sheet by clicking on the grey scrim area
* Try to open the bottom sheet again by clicking on the text

=> The bottom sheet doesn't open again. It continues working if you press the back button.

Assumption: The bottom sheet is not cleared from the backstack if you click on the scrim area.

**Comment by gabrielittner** [comment]
This is a bug in accompanist, specifically what is described in the second part of this comment https://github.com/google/accompanist/issues/1031#issuecomment-1489844606

If you downgrade to to accompanist 0.28.0 (and compose material 1.3.1) the issue goes back to the original description of the linked ticket, meaning that the issue you describe only happens if you dismiss the bottom sheet during the transition.
